nodeLinker: pnp

packageExtensions:
  next-pwa@*:
    dependencies:
      "@babel/core": "*"
      webpack: "*"

plugins:
  - checksum: def112ae4032e04e0f87954008422385c7b293ac27b6813e692009d7291683427d469b11fb261d7d809faf55dd025d60aa2fedd08f8a64f9ef83a98a8cb577cb
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v3.2.0/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.34.cjs
