nodeLinker: pnp

packageExtensions:
  next-pwa@*:
    dependencies:
      "@babel/core": "*"
      webpack: "*"

plugins:
  - checksum: 77be320be9e7821244496574dc3c568ba8e64ae903eec7da5b78437df63a64549b74e2b3fe5a5625d59f9790f3df9d0f6d511f6b31990da310672b29ea88ef05
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v3.1.0/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.33.cjs
